config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'articles/search',to: "articles#search" , as: :articles_search
  resources :articles do
    member do
      post 'increment/:cont', action: :increment, as: :increment
    end
    resources :comments
  end
  # get "/articles", to: "articles#index"

  # get "/articles/:id", to: "articles#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments

    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 10}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def increment
    @article = Article.find(params[:id])
    @cont = params[:cont].to_i + 1
    redirect_to article_path(@article, cont: @cont)
  end
  
  # def search
  #   @articles = Article.where("title LIKE ?", "%#{params[:query]}%")
  #   render :index
  # end

  def index
    @articles = Article.all
    if :query != nil
      @articles = Article.where("title LIKE ?", "%#{params[:query]}%")
    end
    render :index
  end

  def show
    @cont = params.fetch(:cont, 0).to_i
    @articles = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comments = Comment.where(article_id: params[:id])
    @comments.destroy_all
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private 
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
       
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div>
<%= form_with model: article, html: { class: "space-y-6" } do |form| %>
  <div class="space-y-2">
    <%= form.label :Título, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :title, class: "mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div class="text-red-500 text-xs mt-1"><%= message %></div>
    <% end %>
  </div>

  <div class="space-y-2">
    <%= form.label :Párrafo, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_area :body, class: "mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div class="text-red-500 text-xs mt-1"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Crear artículo", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
</div>
<% end %>

app/views/articles/_searchByCategory.html.erb
<form>
    <div class="flex">
        <label for="search-dropdown" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Your Email</label>
        <button id="dropdown-button" data-dropdown-toggle="dropdown" class="flex-shrink-0 z-10 inline-flex items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-gray-300 rounded-s-lg hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-700 dark:text-white dark:border-gray-600" type="button">Título <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
  </svg></button>
        <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
            <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown-button">
            <li>
                <button type="button" class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Título</button>
            </li>
            <li>
                <button type="button" class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Descripción</button>
            </li>
            </ul>
        </div>
        <div class="relative w-full">
            <%= form_with url: articles_search_path, method: :get do |form|%>
            <%= text_field_tag :query, params[:query], placeholder: "Buscar..." %>
            <%= submit_tag "Buscar", class: "absolute top-0 end-0 p-2.5 text-sm font-medium h-full text-white bg-blue-700 rounded-e-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
            <% end %>
        </div>
    </div>
</form>

app/views/articles/edit.html.erb
<div>
<%= link_to 'Volver', :back, class: "px-4 py-2 bg-blue-500 text-white rounded mt-4" %>
<h1 class="text-4xl font-bold mb-4">Editar!</h1>
<%= render "form", article: @article %>

</div>


app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenida</title>
</head>
<body>
<div>
    <div class="container mx-auto px-4">
    <h1 class="text-4xl font-bold mb-4">Artículos</h1>
    <div><%= render "searchByCategory"%></div>
    <ul class="space-y-4">
        <% @articles.each do |t| %>
            <li class="border p-4 rounded shadow">
                <%= link_to t.title, article_path(t), class: "text-blue-500 hover:underline" %>
            </li>
        <% end %>
    </ul>
</div>
<div>
    <%= link_to "Crear Artículo!", new_article_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
</div>
<!-- <h1>artículos funcionamiento link</h1>
    <div>
        <ul>        
            <% @articles.each do |t| %>
                <li>
                    <%= link_to t.body, t %>
                </li>
            <% end %>
        </ul>
        <%= link_to "New article", new_article_path %>
    </div>
    </div> -->
</body>
</html>

app/views/articles/new.html.erb
<div>
<%= link_to 'Volver', :back, class: "px-4 py-2 bg-blue-500 text-white rounded mt-4" %>
<h1 class="text-4xl font-bold mb-4">Nuevo Artículo</h1>
<%= render "form", article: @article %>
</div>

app/views/articles/show.html.erb
<div><%= link_to 'Volver',articles_path,class: "px-4 py-2 bg-blue-500 text-white rounded mt-4" %></div>
<div>
<h1 class="text-4xl font-bold mb-4"> <%= @articles.title  %> </h1>
<p class="text-lg mb-4"> <%= @articles.body  %> </p>
<ul class="list-disc">
  <li class="mb-2"><%= link_to "Editar", edit_article_path(@articles), class: "text-blue-500" %></li>
  <li class="mb-2"><%= link_to "Destruir",article_path(@articles), data: { 
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                    }, class: "text-red-500" %></li>
   
  <li class="mb-2"> <%= @cont %> </li>
<%= form_with url: increment_article_path(cont: @cont), method: :post, class: "mt-4" do %>
  <%= submit_tag "presiona!", class: "px-4 py-2 bg-blue-500 text-white rounded" %>
<% end %>
</ul>

<h2 class="text-2xl font-bold mt-8">Comentarios</h2>
<% @articles.comments.each do |comment| %>
  <div class="bg-gray-100 p-4 rounded mt-4">
    <p>
      <strong>Usuario:</strong>
      <%= comment.commenter %>
    </p>

    <p>
      <strong>Comentario:</strong>
      <%= comment.body %>
    </p>
  </div>
<% end %>

<h2 class="text-2xl font-bold mt-8">Ingresa un comentario:</h2>
<%= form_with model: [ @articles, @articles.comments.build ], class: "mt-4" do |form| %>
  <p class="mb-2">
    <%= form.label :Usuario, class: "font-bold" %><br>
    <%= form.text_field :commenter, class: "border p-2 rounded w-full" %>
  </p>
  <p class="mb-2">
    <%= form.label :Comentario, class: "font-bold" %><br>
    <%= form.text_area :body, class: "border p-2 rounded w-full" %>
  </p>
  <p>
    <%= form.submit "Crear comentario", class: "px-4 py-2 bg-blue-500 text-white rounded" %>
  </p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb


<!-- Modal toggle -->
<button data-modal-target="select-modal" data-modal-toggle="select-modal" class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
  Presioname!
</button>

<!-- Main modal -->
<div id="select-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
                    Aplicaciones disponibles..
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm h-8 w-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="select-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Cerrar modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 md:p-5">
                <p class="text-gray-500 dark:text-gray-400 mb-4">Escoge:</p>
                <ul class="space-y-4 mb-4">
                    <li>
                        <input type="radio" id="job-1" name="job" value="job-1" class="hidden peer" required>
                        <label for="job-1" class="inline-flex items-center justify-between w-full p-5 text-gray-900 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-500 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-900 hover:bg-gray-100 dark:text-white dark:bg-gray-600 dark:hover:bg-gray-500">                           
                            <div class="block">
                                <div class="w-full text-lg font-semibold">CRUD Artículos</div>
                                <div class="w-full text-gray-500 dark:text-gray-400">Flowbite</div>
                            </div>
                            <svg class="w-4 h-4 ms-3 rtl:rotate-180 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/></svg>
                        </label>
                    </li>
                    <li>
                        <input type="radio" id="job-2" name="job" value="job-2" class="hidden peer">
                        <label for="job-2" class="inline-flex items-center justify-between w-full p-5 text-gray-900 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-500 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-900 hover:bg-gray-100 dark:text-white dark:bg-gray-600 dark:hover:bg-gray-500">
                            <div class="block">
                                <div class="w-full text-lg font-semibold">Web Sockets </div>
                                <div class="w-full text-gray-500 dark:text-gray-400">(Coming Soon)</div>
                            </div>
                            <svg class="w-4 h-4 ms-3 rtl:rotate-180 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/></svg>
                        </label>
                    </li>
                    <li>
                        <input type="radio" id="job-3" name="job" value="job-3" class="hidden peer">
                        <label for="job-3" class="inline-flex items-center justify-between w-full p-5 text-gray-900 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-500 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-900 hover:bg-gray-100 dark:text-white dark:bg-gray-600 dark:hover:bg-gray-500">
                            <div class="block">
                                <div class="w-full text-lg font-semibold">Data Analisis </div>
                                <div class="w-full text-gray-500 dark:text-gray-400">(Coming Soon)</div>
                            </div>
                            <svg class="w-4 h-4 ms-3 rtl:rotate-180 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/></svg>
                        </label>
                    </li>
                </ul>
                
                <button class="text-white inline-flex w-full justify-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" onClick="window.location.href='<%=articles_path%>'">
                    Siguiente
                </button>
            </div>
        </div>
    </div>
</div> 